Project_Job_Portal/Controllers/DepartmentsController.cs
using Project_Job_Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;

namespace Project_Job_Portal.Controllers
{
    [Authorize(Roles = "Admin, Users")]
    public class DepartmentsController : Controller
    {
        private readonly CandidateDbContext db = new CandidateDbContext();
        // GET: Departments
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Department model)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(model);
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var data = db.Departments.FirstOrDefault(x => x.DepartmentId == id);
            if (data == null) return new HttpNotFoundResult();
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(Department model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            var department = db.Departments.FirstOrDefault(x => x.DepartmentId == id);
            if (department == null) return new HttpNotFoundResult();
            db.Departments.Remove(department);
            db.SaveChanges();
            return Json(new { success = true });
        }
        public PartialViewResult DepartmentsTable(int pg = 1)
        {
            var data = db.Departments.OrderBy(x => x.DepartmentId).ToPagedList(pg, 5);
            return PartialView("_DepartmentTable", data);
        }
    }
}

Project_Job_Portal/Controllers/GroupingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Project_Job_Portal.Models;
using Project_Job_Portal.ViewModels;

namespace Project_Job_Portal.Controllers
{
    public class GroupingsController : Controller
    {
        private readonly CandidateDbContext db = new CandidateDbContext();
        // GET: Groupings
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GroupingByCandidateName()
        {
            var data = db.Qualifications.Include(x => x.Candidate).ToList()
               .GroupBy(s => s.Candidate.CandidateName)
               .Select(g => new GroupedData { Key = g.Key,Data  = g.Select(x => x) })
               .ToList();
            return View(data);
        }
        public ActionResult GroupingByApplyFor()
        {
            var data = db.Candidates
                .ToList()
               .GroupBy(s => s.AppliedFor)
               .Select(g => new GroupedData { Key = g.Key.ToString(), candidates = g.Select(x => x) })
               .ToList();
            return View(data);
        }
    }
}

Project_Job_Portal/Views/Shared/_Fail.cshtml
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Failed!</strong> Failed to Add New Department.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

Project_Job_Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <style>
        body {
            padding-top: 70px;
        }

        .main {
            min-height: calc(100vh - 110px);
        }
    </style>
    @RenderSection("styles", false)
</head>
<body>


    <navbar class="navbar bg-info-subtle navbar-expand-md fixed-top shadow-sm px-2">
        <div class="container-fluid">
            <span class="navbar-brand">Job Portal Ltd</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nv" aria-controls="nv" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse" id="nv">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Depaetments", "Index", "Departments", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Candidates", "Index", "Candidates", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Aggregates", "Index", "Aggregates", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("GroupingByCandidateName", "GroupingByCandidateName", "Groupings", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("GroupingByApplyFor", "GroupingByApplyFor", "Groupings", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Account", new { }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>

        </div>
    </navbar>
    <main class="container-fluid main">
        @RenderBody()
    </main>
    <footer class="container-fluid">
        <p>&copy; @DateTime.Today.Year Design By Selim</p>
    </footer>
    @RenderSection("scripts", false)
</body>
</html>

Project_Job_Portal/Views/Shared/_Success.cshtml
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> New Department Add.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>