Project_Job_Portal/Controllers/CandidatesController.cs
using Project_Job_Portal.Models;
using Project_Job_Portal.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;
using System.Data.Entity;
using System.Threading;

namespace Project_Job_Portal.Controllers
{
    //[Authorize(Roles = "Admin, Users")]
    public class CandidatesController : Controller
    {
        private readonly CandidateDbContext db = new CandidateDbContext();
        // GET: Candidates
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult CandidateTable(int pg = 1)
        {

            var data = db.Candidates
                .Include(x => x.Qualifications)
                .Include(x => x.Department)
                .OrderBy(x => x.CandidateId)
                .ToPagedList(pg, 2);
            Thread.Sleep(1000);
            return PartialView("_CandidateTable", data);
        }
        //[Authorize(Roles = "Admin")]
        public ActionResult Create()
        {

            return View();
        }
        public ActionResult CreateForm()
        {
            CandidateInputModel model = new CandidateInputModel();
            model.Qualifications.Add(new Qualification());
            ViewBag.Departments = db.Departments.ToList();
            return PartialView("_CreateForm", model);
        }

        [HttpPost]
        public ActionResult Create(CandidateInputModel model, string act = "")
        {
            if (act == "add")
            {
                model.Qualifications.Add(new Qualification());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
                Thread.Sleep(1000);
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Qualifications.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
                Thread.Sleep(1000);
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    var candidate = new Candidate
                    {
                        DepartmentId = model.DepartmentId,
                        CandidateName = model.CandidateName,
                        BirthDate = model.BirthDate,
                        AppliedFor = (Models.AppliedFor)model.AppliedFor,
                        ExpectedSalary = model.ExpectedSalary??0,
                        Conditions = model.Conditions,
                    };
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string f = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Path.Combine(Server.MapPath("~/Pictures"), f);
                    model.Picture.SaveAs(savePath);
                    candidate.Picture = f;


                    db.Candidates.Add(candidate);
                    db.SaveChanges();
                    foreach (var s in model.Qualifications)
                    {
                        //Candidate.Qualification.Add(s);
                        db.Database.ExecuteSqlCommand($"EXEC InsertQualification '{s.Degree}', {(int)s.PassingYear}, '{s.Institute}', '{s.Result}', {candidate.CandidateId}");
                    }

                    CandidateInputModel newmodel = new CandidateInputModel();
                    newmodel.Qualifications.Add(new Qualification());
                    ViewBag.Departments = db.Departments.ToList();
                    foreach (var e in ModelState.Values)
                    {

                        e.Value = null;
                    }
                    return View("_CreateForm", newmodel);
                }
            }
            ViewBag.Departments = db.Departments.ToList();
            return View("_CreateForm", model);
        }
        //[Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {

            ViewBag.Id = id;
            return View();
        }
        public ActionResult EditForm(int id)
        {
            var data = db.Candidates.FirstOrDefault(x => x.CandidateId == id);
            if (data == null) return new HttpNotFoundResult();
            db.Entry(data).Collection(x => x.Qualifications).Load();
            CandidateEditModel model = new CandidateEditModel
            {
                CandidateId = id,
                DepartmentId = data.DepartmentId,
                CandidateName = data.CandidateName,
                BirthDate = data.BirthDate,
                AppliedFor = (ViewModels.AppliedFor)data.AppliedFor,
                ExpectedSalary = data.ExpectedSalary,
                Conditions = data.Conditions,
                Qualifications = data.Qualifications.ToList()
            };
            ViewBag.Departments = db.Departments.ToList();
            ViewBag.CurrentPic = data.Picture;
            return PartialView("_EditForm", model);
        }

        [HttpPost]
        public ActionResult Edit(CandidateEditModel model, string act = "")
        {
            if (act == "add")
            {
                model.Qualifications.Add(new Qualification());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Qualifications.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "update")
            {
                if (ModelState.IsValid)
                {
                    var candidate = db.Candidates.FirstOrDefault(x => x.CandidateId == model.CandidateId);
                    if (candidate == null) { return new HttpNotFoundResult(); }
                    candidate.CandidateName = model.CandidateName;
                    candidate.BirthDate = model.BirthDate;
                    candidate.AppliedFor = (Models.AppliedFor)model.AppliedFor;
                    candidate.ExpectedSalary = model.ExpectedSalary ?? 0;
                    candidate.Conditions = model.Conditions;
                    candidate.DepartmentId = model.DepartmentId;
                    if (model.Picture != null)
                    {
                        string ext = Path.GetExtension(model.Picture.FileName);
                        string f = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Path.Combine(Server.MapPath("~/Pictures"), f);
                        model.Picture.SaveAs(savePath);
                        candidate.Picture = f;
                    }

                    db.SaveChanges();
                    db.Database.ExecuteSqlCommand($"EXEC DeleteQualificationByCandidateId {candidate.CandidateId}");
                    foreach (var s in model.Qualifications)
                    {
                        db.Database.ExecuteSqlCommand($"EXEC InsertQualification '{s.Degree}', {(int)s.PassingYear}, '{s.Institute}', '{s.Result}', {candidate.CandidateId}");
                    }


                }
            }
            ViewBag.Departments = db.Departments.ToList();
            ViewBag.CurrentPic = db.Candidates.FirstOrDefault(x => x.CandidateId == model.CandidateId)?.Picture;
            return View("_EditForm", model);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var qualification = db.Candidates.FirstOrDefault(x => x.CandidateId == id);
            if (qualification == null) return new HttpNotFoundResult();
            db.Candidates.Remove(qualification);
            db.SaveChanges();
            return Json(new { success = true });
        }
    }
}

Project_Job_Portal/Views/Candidates/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
       

        <div id="form-div">
            @Html.Action("CreateForm")
        </div>

    </div>
</div>
@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function onSuccess() {
            $("#frm").trigger("reset");
        }
    </script>

}

Project_Job_Portal/Views/Candidates/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        
        <div id="form-div">
            @Html.Action("EditForm", new { id = ViewBag.Id })

        </div>
    </div>
</div>
@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function onSuccess() {
            $("#frm").trigger("reset");
        }
    </script>

}

Project_Job_Portal/Views/Candidates/Index.cshtml
@model IEnumerable<Project_Job_Portal.Models.Candidate>
@{
    ViewBag.Title = "Index";
}
<h3>Candidate List</h3>
<div class="row">
    <div class="col-12">

        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Create New", "Create", "Candidates", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <div class="spinner-border text-danger" role="status" id="spinner" style="display:none">
            <span class="visually-hidden">Loading...</span>
        </div>
        <div id="table-div">
            @Html.Action("CandidateTable", "Candidates")
        </div>
    </div>

</div>
@section styles
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
}
@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(document).on("click", "button.show", function () {
            var showBtn = $(this);
            var hideBtn = showBtn.next();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.hide();
            hideBtn.show();
            trSt.show();
        });
        $(document).on("click", "button.hide", function () {
            var hideBtn = $(this);
            var showBtn = hideBtn.prev();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.show();
            hideBtn.hide();
            trSt.hide();
        });
        $(document).on("click", "button.del", function () {
            var id = $(this).data("pk");
            var trP = $(this).closest('tr');
            var trS = trP.next();
            if (confirm("Are you sure to delete?\nCandidate with Qualifications will be deleted.")) {
                $.ajax({
                    url: "/Candidates/Delete/" + id,
                    method: "post",
                    dataType: "json",
                    success: r => {
                        if (r.success == true) {
                            trP.remove();
                            trS.remove();
                        }
                    }
                })
            }
        });
    </script>
}

Project_Job_Portal/Views/Candidates/_CandidateTable.cshtml
@model IEnumerable<Project_Job_Portal.Models.Candidate>
@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common

<table class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>Image</th>
            <th>DepartmentName</th> 
            <th>CandidateName</th>
            <th>BirthDate</th>
            <th>AppliedFor</th>
            <th>ExpectedSalary</th>
            <th>Conditions?</th>
            <th>...</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td style="width:40px;text-align:center">
                    <button class="btn btn-sm show"><i class="bi bi-plus-square"></i></button>
                    <button class="btn btn-sm hide" style="display:none"><i class="bi bi-dash-square"></i></button>
                </td>
                <td style="width:45px;text-align:center"><img src="~/Pictures/@s.Picture" class="rounded-circle" style="width:40px" /></td>
                <td>@s.Department.DepartmentName</td>
                <td>@s.CandidateName</td>
                <td>@s.BirthDate.ToString("yyyy-MM-dd")</td>
                <td>@s.AppliedFor</td>
                <td>@s.ExpectedSalary</td>
                <td>@(s.Conditions ? "Yes": "No")</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Candidates", new { id = s.CandidateId }, new { @class = "btn btn-primary btn-sm" })
                    <button type="button" data-pk="@s.CandidateId" class="btn btn-danger btn-sm del">Delete</button>
                </td>
            </tr>
            <tr style="display:none">
                <td></td>
                <td colspan="8">
                    <h4>Qualifications</h4>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Degree</th>
                                <th>PassingYear</th>
                                <th>Institute</th>
                                <th>Result</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var p in s.Qualifications)
                            {
                                <tr>
                                    <td>@p.Degree</td>
                                    <td>@p.PassingYear</td>
                                    <td>@p.Institute</td>
                                    <td>@p.Result</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-end">

    @Html.PagedListPager((IPagedList)Model, pg => Url.Action("CandidateTable", "Candidates", new { pg = pg }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
    {
        UlElementClasses = new string[] { "pagination", "pagination-sm" },
        LiElementClasses = new string[] { "page-item" },
        PageClasses = new string[] { "page-link" },
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        DisplayLinkToNextPage = PagedListDisplayMode.Always
    },
    new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "table-div",LoadingElementId="spinner" }))
</div>

Project_Job_Portal/Views/Candidates/_CreateForm.cshtml
@model Project_Job_Portal.ViewModels.CandidateInputModel
@using (Ajax.BeginForm("Create",
    "Candidates", new { },
    new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "form-div",
        OnSuccess = "onSuccess"
    },
    new { id = "frm", enctype = "multipart/form-data" }))
{
    <h3>Add new Candidate</h3>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.DepartmentId, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.DepartmentId, new SelectList(ViewBag.Departments, "DepartmentId", "DepartmentName"), "Select Department", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.DepartmentId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.CandidateName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.CandidateName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CandidateName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BirthDate, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.BirthDate, new { @class = "form-control", type = "date", @Value = DateTime.Today.ToString("yyyy-MM-dd") })
            @Html.ValidationMessageFor(x => x.BirthDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.AppliedFor, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.EnumDropDownListFor(x => x.AppliedFor, new { @class = "form-select form-control-sm" })
            @Html.ValidationMessageFor(x => x.AppliedFor, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.ExpectedSalary, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.ExpectedSalary, new { @class = "form-control",type="number" })
            @Html.ValidationMessageFor(x => x.ExpectedSalary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">

        @Html.LabelFor(x => x.Conditions, new { @class = "col-form-label col-form-label-sm col-2 text-end" })
        <div class="col-4">
            @Html.CheckBoxFor(x => x.Conditions)
            @Html.ValidationMessageFor(x => x.Conditions, "", new { @class = "text-danger", style = "font-size:small" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-4 offset-2">
            <div class="d-flex justify-content-between">
                <h4>Qualifications</h4>
                <button class="btn btn-sm" type="submit" name="act" value="add" formnovalidate>Add</button>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Degree</th>
                        <th>Institute</th>
                        <th>Passing Year</th>
                        <th>Result</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.Qualifications.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.TextBoxFor(x => Model.Qualifications[i].Degree, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Qualifications[i].Degree, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Qualifications[i].Institute, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Qualifications[i].Institute, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Qualifications[i].PassingYear, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Qualifications[i].PassingYear, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Qualifications[i].Result, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Qualifications[i].Result, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="form-group row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" name="act" value="insert" class="btn btn-primary">Save</button>
        </div>
    </div>
}
<div class="col-12">
    @Html.ActionLink("Back to Candidate list", "Index")
</div>

Project_Job_Portal/Views/Candidates/_EditForm.cshtml
@model Project_Job_Portal.ViewModels.CandidateEditModel
@using (Ajax.BeginForm("Edit",
    "Candidates", new { },
    new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "form-div",
        OnSuccess = "onSuccess"
    },
    new { id = "frm", enctype = "multipart/form-data" }))
{
    <h3>Edit Candidate</h3>
    @Html.HiddenFor(x => x.CandidateId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.DepartmentId, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.DepartmentId, new SelectList(ViewBag.Departments, "DepartmentId", "DepartmentName"), "Select Department", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.DepartmentId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.CandidateName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.CandidateName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CandidateName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BirthDate, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.BirthDate, new { @class = "form-control", type = "date", @Value = DateTime.Today.ToString("yyyy-MM-dd") })
            @Html.ValidationMessageFor(x => x.BirthDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.AppliedFor, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.EnumDropDownListFor(x => x.AppliedFor, new { @class = "form-select form-control-sm" })
            @Html.ValidationMessageFor(x => x.AppliedFor, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.ExpectedSalary, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.ExpectedSalary, new { @class = "form-control", type = "number" })
            @Html.ValidationMessageFor(x => x.ExpectedSalary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
        <div class="col-1">
            <img src="~/Pictures/@ViewBag.CurreentPic" style="width:35px" class="img-thumbnail" />
        </div>
    </div>
    <div class="form-group row mb-1">

        @Html.LabelFor(x => x.Conditions, new { @class = "col-form-label col-form-label-sm col-2 text-end" })
        <div class="col-4">
            @Html.CheckBoxFor(x => x.Conditions)
            @Html.ValidationMessageFor(x => x.Conditions, "", new { @class = "text-danger", style = "font-size:small" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-4 offset-2">
            <div class="d-flex justify-content-between">
                <h4>Qualifications</h4>
                <button class="btn btn-sm" type="submit" name="act" value="add" formnovalidate>Add</button>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Degree</th>
                        <th>Institute</th>
                        <th>Passing Year</th>
                        <th>Result</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.Qualifications.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.TextBoxFor(x => Model.Qualifications[i].Degree, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Qualifications[i].Degree, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Qualifications[i].Institute, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Qualifications[i].Institute, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Qualifications[i].PassingYear, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Qualifications[i].PassingYear, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Qualifications[i].Result, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Qualifications[i].Result, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="form-group row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" name="act" value="update" class="btn btn-primary">Save</button>
        </div>
    </div>
}
<div class="col-12">
    @Html.ActionLink("Back to Candidate list", "Index")
</div>